// Code generated by go-swagger; DO NOT EDIT.

package clusters

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/zalando-incubator/cluster-lifecycle-manager/pkg/cluster-registry/models"
)

// CreateClusterReader is a Reader for the CreateCluster structure.
type CreateClusterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateClusterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateClusterCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateClusterBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateClusterUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateClusterForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewCreateClusterConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateClusterInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateClusterCreated creates a CreateClusterCreated with default headers values
func NewCreateClusterCreated() *CreateClusterCreated {
	return &CreateClusterCreated{}
}

/*
CreateClusterCreated describes a response with status code 201, with default header values.

The cluster creation request is accepted
*/
type CreateClusterCreated struct {
	Payload *models.Cluster
}

// IsSuccess returns true when this create cluster created response has a 2xx status code
func (o *CreateClusterCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create cluster created response has a 3xx status code
func (o *CreateClusterCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create cluster created response has a 4xx status code
func (o *CreateClusterCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create cluster created response has a 5xx status code
func (o *CreateClusterCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create cluster created response a status code equal to that given
func (o *CreateClusterCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create cluster created response
func (o *CreateClusterCreated) Code() int {
	return 201
}

func (o *CreateClusterCreated) Error() string {
	return fmt.Sprintf("[POST /kubernetes-clusters][%d] createClusterCreated  %+v", 201, o.Payload)
}

func (o *CreateClusterCreated) String() string {
	return fmt.Sprintf("[POST /kubernetes-clusters][%d] createClusterCreated  %+v", 201, o.Payload)
}

func (o *CreateClusterCreated) GetPayload() *models.Cluster {
	return o.Payload
}

func (o *CreateClusterCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Cluster)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateClusterBadRequest creates a CreateClusterBadRequest with default headers values
func NewCreateClusterBadRequest() *CreateClusterBadRequest {
	return &CreateClusterBadRequest{}
}

/*
CreateClusterBadRequest describes a response with status code 400, with default header values.

Invalid request
*/
type CreateClusterBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this create cluster bad request response has a 2xx status code
func (o *CreateClusterBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create cluster bad request response has a 3xx status code
func (o *CreateClusterBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create cluster bad request response has a 4xx status code
func (o *CreateClusterBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create cluster bad request response has a 5xx status code
func (o *CreateClusterBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create cluster bad request response a status code equal to that given
func (o *CreateClusterBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create cluster bad request response
func (o *CreateClusterBadRequest) Code() int {
	return 400
}

func (o *CreateClusterBadRequest) Error() string {
	return fmt.Sprintf("[POST /kubernetes-clusters][%d] createClusterBadRequest  %+v", 400, o.Payload)
}

func (o *CreateClusterBadRequest) String() string {
	return fmt.Sprintf("[POST /kubernetes-clusters][%d] createClusterBadRequest  %+v", 400, o.Payload)
}

func (o *CreateClusterBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateClusterBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateClusterUnauthorized creates a CreateClusterUnauthorized with default headers values
func NewCreateClusterUnauthorized() *CreateClusterUnauthorized {
	return &CreateClusterUnauthorized{}
}

/*
CreateClusterUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type CreateClusterUnauthorized struct {
}

// IsSuccess returns true when this create cluster unauthorized response has a 2xx status code
func (o *CreateClusterUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create cluster unauthorized response has a 3xx status code
func (o *CreateClusterUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create cluster unauthorized response has a 4xx status code
func (o *CreateClusterUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create cluster unauthorized response has a 5xx status code
func (o *CreateClusterUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create cluster unauthorized response a status code equal to that given
func (o *CreateClusterUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the create cluster unauthorized response
func (o *CreateClusterUnauthorized) Code() int {
	return 401
}

func (o *CreateClusterUnauthorized) Error() string {
	return fmt.Sprintf("[POST /kubernetes-clusters][%d] createClusterUnauthorized ", 401)
}

func (o *CreateClusterUnauthorized) String() string {
	return fmt.Sprintf("[POST /kubernetes-clusters][%d] createClusterUnauthorized ", 401)
}

func (o *CreateClusterUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateClusterForbidden creates a CreateClusterForbidden with default headers values
func NewCreateClusterForbidden() *CreateClusterForbidden {
	return &CreateClusterForbidden{}
}

/*
CreateClusterForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type CreateClusterForbidden struct {
}

// IsSuccess returns true when this create cluster forbidden response has a 2xx status code
func (o *CreateClusterForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create cluster forbidden response has a 3xx status code
func (o *CreateClusterForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create cluster forbidden response has a 4xx status code
func (o *CreateClusterForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create cluster forbidden response has a 5xx status code
func (o *CreateClusterForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create cluster forbidden response a status code equal to that given
func (o *CreateClusterForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the create cluster forbidden response
func (o *CreateClusterForbidden) Code() int {
	return 403
}

func (o *CreateClusterForbidden) Error() string {
	return fmt.Sprintf("[POST /kubernetes-clusters][%d] createClusterForbidden ", 403)
}

func (o *CreateClusterForbidden) String() string {
	return fmt.Sprintf("[POST /kubernetes-clusters][%d] createClusterForbidden ", 403)
}

func (o *CreateClusterForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateClusterConflict creates a CreateClusterConflict with default headers values
func NewCreateClusterConflict() *CreateClusterConflict {
	return &CreateClusterConflict{}
}

/*
CreateClusterConflict describes a response with status code 409, with default header values.

Conflict, already existing
*/
type CreateClusterConflict struct {
}

// IsSuccess returns true when this create cluster conflict response has a 2xx status code
func (o *CreateClusterConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create cluster conflict response has a 3xx status code
func (o *CreateClusterConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create cluster conflict response has a 4xx status code
func (o *CreateClusterConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this create cluster conflict response has a 5xx status code
func (o *CreateClusterConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this create cluster conflict response a status code equal to that given
func (o *CreateClusterConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the create cluster conflict response
func (o *CreateClusterConflict) Code() int {
	return 409
}

func (o *CreateClusterConflict) Error() string {
	return fmt.Sprintf("[POST /kubernetes-clusters][%d] createClusterConflict ", 409)
}

func (o *CreateClusterConflict) String() string {
	return fmt.Sprintf("[POST /kubernetes-clusters][%d] createClusterConflict ", 409)
}

func (o *CreateClusterConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateClusterInternalServerError creates a CreateClusterInternalServerError with default headers values
func NewCreateClusterInternalServerError() *CreateClusterInternalServerError {
	return &CreateClusterInternalServerError{}
}

/*
CreateClusterInternalServerError describes a response with status code 500, with default header values.

Unexpected error
*/
type CreateClusterInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this create cluster internal server error response has a 2xx status code
func (o *CreateClusterInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create cluster internal server error response has a 3xx status code
func (o *CreateClusterInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create cluster internal server error response has a 4xx status code
func (o *CreateClusterInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create cluster internal server error response has a 5xx status code
func (o *CreateClusterInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create cluster internal server error response a status code equal to that given
func (o *CreateClusterInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create cluster internal server error response
func (o *CreateClusterInternalServerError) Code() int {
	return 500
}

func (o *CreateClusterInternalServerError) Error() string {
	return fmt.Sprintf("[POST /kubernetes-clusters][%d] createClusterInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateClusterInternalServerError) String() string {
	return fmt.Sprintf("[POST /kubernetes-clusters][%d] createClusterInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateClusterInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateClusterInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
