// Code generated by go-swagger; DO NOT EDIT.

package clusters

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
)

// NewGetClusterParams creates a new GetClusterParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetClusterParams() *GetClusterParams {
	return NewGetClusterParamsWithTimeout(cr.DefaultTimeout)
}

// NewGetClusterParamsWithTimeout creates a new GetClusterParams object
// with the ability to set a timeout on a request.
func NewGetClusterParamsWithTimeout(timeout time.Duration) *GetClusterParams {
	return &GetClusterParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewGetClusterParamsWithContext creates a new GetClusterParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [GetClusterParams].
func NewGetClusterParamsWithContext(ctx context.Context) *GetClusterParams {
	return &GetClusterParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewGetClusterParamsWithHTTPClient creates a new GetClusterParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetClusterParamsWithHTTPClient(client *http.Client) *GetClusterParams {
	return &GetClusterParams{
		HTTPClient: client,
	}
}

/*
GetClusterParams contains all the parameters to send to the API endpoint

	for the get cluster operation.

	Typically these are written to a http.Request.
*/
type GetClusterParams struct {

	// ClusterID.
	//
	// ID of the cluster.
	ClusterID string

	// Verbose.
	//
	// Include technical data (config items, node pools) in the response, true by default
	//
	// Default: true
	Verbose *bool

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the get cluster params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetClusterParams) WithDefaults() *GetClusterParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get cluster params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetClusterParams) SetDefaults() {
	var (
		verboseDefault = bool(true)
	)

	val := GetClusterParams{
		Verbose: &verboseDefault,
	}

	val.inner.timeout = o.inner.timeout
	val.inner.ctx = o.inner.ctx
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get cluster params.
func (o *GetClusterParams) WithTimeout(timeout time.Duration) *GetClusterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get cluster params.
func (o *GetClusterParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the get cluster params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetClusterParams].
func (o *GetClusterParams) WithContext(ctx context.Context) *GetClusterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get cluster params.
//
// Deprecated: use the operation call with context to pass the context instead of [GetClusterParams].
func (o *GetClusterParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the get cluster params.
func (o *GetClusterParams) WithHTTPClient(client *http.Client) *GetClusterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get cluster params.
func (o *GetClusterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterID adds the clusterID to the get cluster params.
func (o *GetClusterParams) WithClusterID(clusterID string) *GetClusterParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the get cluster params.
func (o *GetClusterParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithVerbose adds the verbose to the get cluster params.
func (o *GetClusterParams) WithVerbose(verbose *bool) *GetClusterParams {
	o.SetVerbose(verbose)
	return o
}

// SetVerbose adds the verbose to the get cluster params.
func (o *GetClusterParams) SetVerbose(verbose *bool) {
	o.Verbose = verbose
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *GetClusterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}

	if o.Verbose != nil {

		// query param verbose
		var qrVerbose bool

		if o.Verbose != nil {
			qrVerbose = *o.Verbose
		}
		qVerbose := conv.FormatBool(qrVerbose)
		if qVerbose != "" {

			if err := r.SetQueryParam("verbose", qVerbose); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
