// Code generated by go-swagger; DO NOT EDIT.

package node_pools

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/zalando-incubator/cluster-lifecycle-manager/pkg/cluster-registry/models"
)

// CreateOrUpdateNodePoolReader is a Reader for the CreateOrUpdateNodePool structure.
type CreateOrUpdateNodePoolReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateOrUpdateNodePoolReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewCreateOrUpdateNodePoolOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateOrUpdateNodePoolBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateOrUpdateNodePoolUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateOrUpdateNodePoolForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateOrUpdateNodePoolInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PUT /kubernetes-clusters/{cluster_id}/node-pools/{node_pool_name}] createOrUpdateNodePool", response, response.Code())
	}
}

// NewCreateOrUpdateNodePoolOK creates a CreateOrUpdateNodePoolOK with default headers values
func NewCreateOrUpdateNodePoolOK() *CreateOrUpdateNodePoolOK {
	return &CreateOrUpdateNodePoolOK{}
}

/*
CreateOrUpdateNodePoolOK describes a response with status code 200, with default header values.

The node pool create request is accepted.
*/
type CreateOrUpdateNodePoolOK struct {
	Payload *models.NodePool
}

// IsSuccess returns true when this create or update node pool o k response has a 2xx status code
func (o *CreateOrUpdateNodePoolOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create or update node pool o k response has a 3xx status code
func (o *CreateOrUpdateNodePoolOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create or update node pool o k response has a 4xx status code
func (o *CreateOrUpdateNodePoolOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create or update node pool o k response has a 5xx status code
func (o *CreateOrUpdateNodePoolOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create or update node pool o k response a status code equal to that given
func (o *CreateOrUpdateNodePoolOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create or update node pool o k response
func (o *CreateOrUpdateNodePoolOK) Code() int {
	return 200
}

func (o *CreateOrUpdateNodePoolOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /kubernetes-clusters/{cluster_id}/node-pools/{node_pool_name}][%d] createOrUpdateNodePoolOK %s", 200, payload)
}

func (o *CreateOrUpdateNodePoolOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /kubernetes-clusters/{cluster_id}/node-pools/{node_pool_name}][%d] createOrUpdateNodePoolOK %s", 200, payload)
}

func (o *CreateOrUpdateNodePoolOK) GetPayload() *models.NodePool {
	return o.Payload
}

func (o *CreateOrUpdateNodePoolOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NodePool)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateOrUpdateNodePoolBadRequest creates a CreateOrUpdateNodePoolBadRequest with default headers values
func NewCreateOrUpdateNodePoolBadRequest() *CreateOrUpdateNodePoolBadRequest {
	return &CreateOrUpdateNodePoolBadRequest{}
}

/*
CreateOrUpdateNodePoolBadRequest describes a response with status code 400, with default header values.

Invalid request
*/
type CreateOrUpdateNodePoolBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this create or update node pool bad request response has a 2xx status code
func (o *CreateOrUpdateNodePoolBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create or update node pool bad request response has a 3xx status code
func (o *CreateOrUpdateNodePoolBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create or update node pool bad request response has a 4xx status code
func (o *CreateOrUpdateNodePoolBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create or update node pool bad request response has a 5xx status code
func (o *CreateOrUpdateNodePoolBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create or update node pool bad request response a status code equal to that given
func (o *CreateOrUpdateNodePoolBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create or update node pool bad request response
func (o *CreateOrUpdateNodePoolBadRequest) Code() int {
	return 400
}

func (o *CreateOrUpdateNodePoolBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /kubernetes-clusters/{cluster_id}/node-pools/{node_pool_name}][%d] createOrUpdateNodePoolBadRequest %s", 400, payload)
}

func (o *CreateOrUpdateNodePoolBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /kubernetes-clusters/{cluster_id}/node-pools/{node_pool_name}][%d] createOrUpdateNodePoolBadRequest %s", 400, payload)
}

func (o *CreateOrUpdateNodePoolBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateOrUpdateNodePoolBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateOrUpdateNodePoolUnauthorized creates a CreateOrUpdateNodePoolUnauthorized with default headers values
func NewCreateOrUpdateNodePoolUnauthorized() *CreateOrUpdateNodePoolUnauthorized {
	return &CreateOrUpdateNodePoolUnauthorized{}
}

/*
CreateOrUpdateNodePoolUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type CreateOrUpdateNodePoolUnauthorized struct {
}

// IsSuccess returns true when this create or update node pool unauthorized response has a 2xx status code
func (o *CreateOrUpdateNodePoolUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create or update node pool unauthorized response has a 3xx status code
func (o *CreateOrUpdateNodePoolUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create or update node pool unauthorized response has a 4xx status code
func (o *CreateOrUpdateNodePoolUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create or update node pool unauthorized response has a 5xx status code
func (o *CreateOrUpdateNodePoolUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create or update node pool unauthorized response a status code equal to that given
func (o *CreateOrUpdateNodePoolUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the create or update node pool unauthorized response
func (o *CreateOrUpdateNodePoolUnauthorized) Code() int {
	return 401
}

func (o *CreateOrUpdateNodePoolUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /kubernetes-clusters/{cluster_id}/node-pools/{node_pool_name}][%d] createOrUpdateNodePoolUnauthorized", 401)
}

func (o *CreateOrUpdateNodePoolUnauthorized) String() string {
	return fmt.Sprintf("[PUT /kubernetes-clusters/{cluster_id}/node-pools/{node_pool_name}][%d] createOrUpdateNodePoolUnauthorized", 401)
}

func (o *CreateOrUpdateNodePoolUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateOrUpdateNodePoolForbidden creates a CreateOrUpdateNodePoolForbidden with default headers values
func NewCreateOrUpdateNodePoolForbidden() *CreateOrUpdateNodePoolForbidden {
	return &CreateOrUpdateNodePoolForbidden{}
}

/*
CreateOrUpdateNodePoolForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type CreateOrUpdateNodePoolForbidden struct {
}

// IsSuccess returns true when this create or update node pool forbidden response has a 2xx status code
func (o *CreateOrUpdateNodePoolForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create or update node pool forbidden response has a 3xx status code
func (o *CreateOrUpdateNodePoolForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create or update node pool forbidden response has a 4xx status code
func (o *CreateOrUpdateNodePoolForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create or update node pool forbidden response has a 5xx status code
func (o *CreateOrUpdateNodePoolForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create or update node pool forbidden response a status code equal to that given
func (o *CreateOrUpdateNodePoolForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the create or update node pool forbidden response
func (o *CreateOrUpdateNodePoolForbidden) Code() int {
	return 403
}

func (o *CreateOrUpdateNodePoolForbidden) Error() string {
	return fmt.Sprintf("[PUT /kubernetes-clusters/{cluster_id}/node-pools/{node_pool_name}][%d] createOrUpdateNodePoolForbidden", 403)
}

func (o *CreateOrUpdateNodePoolForbidden) String() string {
	return fmt.Sprintf("[PUT /kubernetes-clusters/{cluster_id}/node-pools/{node_pool_name}][%d] createOrUpdateNodePoolForbidden", 403)
}

func (o *CreateOrUpdateNodePoolForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateOrUpdateNodePoolInternalServerError creates a CreateOrUpdateNodePoolInternalServerError with default headers values
func NewCreateOrUpdateNodePoolInternalServerError() *CreateOrUpdateNodePoolInternalServerError {
	return &CreateOrUpdateNodePoolInternalServerError{}
}

/*
CreateOrUpdateNodePoolInternalServerError describes a response with status code 500, with default header values.

Unexpected error
*/
type CreateOrUpdateNodePoolInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this create or update node pool internal server error response has a 2xx status code
func (o *CreateOrUpdateNodePoolInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create or update node pool internal server error response has a 3xx status code
func (o *CreateOrUpdateNodePoolInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create or update node pool internal server error response has a 4xx status code
func (o *CreateOrUpdateNodePoolInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create or update node pool internal server error response has a 5xx status code
func (o *CreateOrUpdateNodePoolInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create or update node pool internal server error response a status code equal to that given
func (o *CreateOrUpdateNodePoolInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create or update node pool internal server error response
func (o *CreateOrUpdateNodePoolInternalServerError) Code() int {
	return 500
}

func (o *CreateOrUpdateNodePoolInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /kubernetes-clusters/{cluster_id}/node-pools/{node_pool_name}][%d] createOrUpdateNodePoolInternalServerError %s", 500, payload)
}

func (o *CreateOrUpdateNodePoolInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /kubernetes-clusters/{cluster_id}/node-pools/{node_pool_name}][%d] createOrUpdateNodePoolInternalServerError %s", 500, payload)
}

func (o *CreateOrUpdateNodePoolInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateOrUpdateNodePoolInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
