// Code generated by go-swagger; DO NOT EDIT.

package node_pools

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/zalando-incubator/cluster-lifecycle-manager/pkg/cluster-registry/models"
)

// CreateOrUpdateNodePoolReader is a Reader for the CreateOrUpdateNodePool structure.
type CreateOrUpdateNodePoolReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateOrUpdateNodePoolReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateOrUpdateNodePoolOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateOrUpdateNodePoolBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateOrUpdateNodePoolUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateOrUpdateNodePoolForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateOrUpdateNodePoolInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateOrUpdateNodePoolOK creates a CreateOrUpdateNodePoolOK with default headers values
func NewCreateOrUpdateNodePoolOK() *CreateOrUpdateNodePoolOK {
	return &CreateOrUpdateNodePoolOK{}
}

/*CreateOrUpdateNodePoolOK handles this case with default header values.

The node pool create request is accepted.
*/
type CreateOrUpdateNodePoolOK struct {
	Payload *models.NodePool
}

func (o *CreateOrUpdateNodePoolOK) Error() string {
	return fmt.Sprintf("[PUT /kubernetes-clusters/{cluster_id}/node-pools/{node_pool_name}][%d] createOrUpdateNodePoolOK  %+v", 200, o.Payload)
}

func (o *CreateOrUpdateNodePoolOK) GetPayload() *models.NodePool {
	return o.Payload
}

func (o *CreateOrUpdateNodePoolOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.NodePool)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateOrUpdateNodePoolBadRequest creates a CreateOrUpdateNodePoolBadRequest with default headers values
func NewCreateOrUpdateNodePoolBadRequest() *CreateOrUpdateNodePoolBadRequest {
	return &CreateOrUpdateNodePoolBadRequest{}
}

/*CreateOrUpdateNodePoolBadRequest handles this case with default header values.

Invalid request
*/
type CreateOrUpdateNodePoolBadRequest struct {
	Payload *models.Error
}

func (o *CreateOrUpdateNodePoolBadRequest) Error() string {
	return fmt.Sprintf("[PUT /kubernetes-clusters/{cluster_id}/node-pools/{node_pool_name}][%d] createOrUpdateNodePoolBadRequest  %+v", 400, o.Payload)
}

func (o *CreateOrUpdateNodePoolBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateOrUpdateNodePoolBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateOrUpdateNodePoolUnauthorized creates a CreateOrUpdateNodePoolUnauthorized with default headers values
func NewCreateOrUpdateNodePoolUnauthorized() *CreateOrUpdateNodePoolUnauthorized {
	return &CreateOrUpdateNodePoolUnauthorized{}
}

/*CreateOrUpdateNodePoolUnauthorized handles this case with default header values.

Unauthorized
*/
type CreateOrUpdateNodePoolUnauthorized struct {
}

func (o *CreateOrUpdateNodePoolUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /kubernetes-clusters/{cluster_id}/node-pools/{node_pool_name}][%d] createOrUpdateNodePoolUnauthorized ", 401)
}

func (o *CreateOrUpdateNodePoolUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateOrUpdateNodePoolForbidden creates a CreateOrUpdateNodePoolForbidden with default headers values
func NewCreateOrUpdateNodePoolForbidden() *CreateOrUpdateNodePoolForbidden {
	return &CreateOrUpdateNodePoolForbidden{}
}

/*CreateOrUpdateNodePoolForbidden handles this case with default header values.

Forbidden
*/
type CreateOrUpdateNodePoolForbidden struct {
}

func (o *CreateOrUpdateNodePoolForbidden) Error() string {
	return fmt.Sprintf("[PUT /kubernetes-clusters/{cluster_id}/node-pools/{node_pool_name}][%d] createOrUpdateNodePoolForbidden ", 403)
}

func (o *CreateOrUpdateNodePoolForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateOrUpdateNodePoolInternalServerError creates a CreateOrUpdateNodePoolInternalServerError with default headers values
func NewCreateOrUpdateNodePoolInternalServerError() *CreateOrUpdateNodePoolInternalServerError {
	return &CreateOrUpdateNodePoolInternalServerError{}
}

/*CreateOrUpdateNodePoolInternalServerError handles this case with default header values.

Unexpected error
*/
type CreateOrUpdateNodePoolInternalServerError struct {
	Payload *models.Error
}

func (o *CreateOrUpdateNodePoolInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /kubernetes-clusters/{cluster_id}/node-pools/{node_pool_name}][%d] createOrUpdateNodePoolInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateOrUpdateNodePoolInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateOrUpdateNodePoolInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
