// Code generated by go-swagger; DO NOT EDIT.

package node_pools

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListNodePoolsParams creates a new ListNodePoolsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListNodePoolsParams() *ListNodePoolsParams {
	return NewListNodePoolsParamsWithTimeout(cr.DefaultTimeout)
}

// NewListNodePoolsParamsWithTimeout creates a new ListNodePoolsParams object
// with the ability to set a timeout on a request.
func NewListNodePoolsParamsWithTimeout(timeout time.Duration) *ListNodePoolsParams {
	return &ListNodePoolsParams{
		inner: innerParams{
			timeout: timeout,
		},
	}
}

// NewListNodePoolsParamsWithContext creates a new ListNodePoolsParams object
// with the ability to set a context for a request.
//
// Deprecated: use the operation call with context to pass the context instead of [ListNodePoolsParams].
func NewListNodePoolsParamsWithContext(ctx context.Context) *ListNodePoolsParams {
	return &ListNodePoolsParams{
		inner: innerParams{
			ctx: ctx,
		},
	}
}

// NewListNodePoolsParamsWithHTTPClient creates a new ListNodePoolsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListNodePoolsParamsWithHTTPClient(client *http.Client) *ListNodePoolsParams {
	return &ListNodePoolsParams{
		HTTPClient: client,
	}
}

/*
ListNodePoolsParams contains all the parameters to send to the API endpoint

	for the list node pools operation.

	Typically these are written to a http.Request.
*/
type ListNodePoolsParams struct {

	// ClusterID.
	//
	// ID of the cluster.
	ClusterID string

	HTTPClient *http.Client

	inner innerParams
}

// WithDefaults hydrates default values in the list node pools params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListNodePoolsParams) WithDefaults() *ListNodePoolsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list node pools params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListNodePoolsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list node pools params.
func (o *ListNodePoolsParams) WithTimeout(timeout time.Duration) *ListNodePoolsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list node pools params.
func (o *ListNodePoolsParams) SetTimeout(timeout time.Duration) {
	o.inner.timeout = timeout
}

// WithContext adds the context to the list node pools params.
//
// Deprecated: use the operation call with context to pass the context instead of [ListNodePoolsParams].
func (o *ListNodePoolsParams) WithContext(ctx context.Context) *ListNodePoolsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list node pools params.
//
// Deprecated: use the operation call with context to pass the context instead of [ListNodePoolsParams].
func (o *ListNodePoolsParams) SetContext(ctx context.Context) {
	o.inner.ctx = ctx
}

// WithHTTPClient adds the HTTPClient to the list node pools params.
func (o *ListNodePoolsParams) WithHTTPClient(client *http.Client) *ListNodePoolsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list node pools params.
func (o *ListNodePoolsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterID adds the clusterID to the list node pools params.
func (o *ListNodePoolsParams) WithClusterID(clusterID string) *ListNodePoolsParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the list node pools params.
func (o *ListNodePoolsParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WriteToRequest writes these params to a [runtime.ClientRequest].
func (o *ListNodePoolsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {
	if err := r.SetTimeout(o.inner.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
