version: "2017-09-20"
pipeline:
- id: build
  overlay: ci/golang
  type: script
  working_dir: /go/src/github.com/zalando-incubator/cluster-lifecycle-manager
  commands:
  - desc: install deps
    cmd: |
      dep ensure -v -vendor-only
  - desc: test
    cmd: |
      make test
  - desc: static checks
    cmd: |
      make staticcheck
  - desc: build
    cmd: |
      make build.docker
  - desc: push
    cmd: |
      if [[ $CDP_TARGET_BRANCH == master && ! $CDP_PULL_REQUEST_NUMBER ]]; then
        IMAGE=registry-write.opensource.zalan.do/teapot/cluster-lifecycle-manager
        VERSION=$(git describe --tags --always --dirty)
      else
        IMAGE=registry-write.opensource.zalan.do/teapot/cluster-lifecycle-manager-test
        VERSION=$CDP_BUILD_VERSION
      fi
      IMAGE=$IMAGE VERSION=$VERSION make build.push

notifications:
  hipchat:
    rooms:
    - "Teapot CICD"
