version: "2017-09-20"
pipeline:
- id: build
  overlay: ci/golang
  type: script
  env:
    GOFLAGS: "-mod=readonly"
  vm: large
  cache:
    paths:
    - /go/pkg/mod
    - ~/.cache/go-build
  commands:
  - desc: test & check
    cmd: |
      make lint
      make test
  - desc: build
    cmd: |
      make build.docker
  - desc: push
    cmd: |
      git status
      if [[ $CDP_TARGET_BRANCH == master && ! $CDP_PULL_REQUEST_NUMBER ]]; then
        IMAGE=registry-write.opensource.zalan.do/teapot/cluster-lifecycle-manager
        VERSION=$(git describe --tags --always --dirty)
      else
        IMAGE=registry-write.opensource.zalan.do/teapot/cluster-lifecycle-manager-test
        VERSION=$CDP_BUILD_VERSION
      fi
      IMAGE=$IMAGE VERSION=$VERSION make build.push
