// Code generated by go-swagger; DO NOT EDIT.

package infrastructure_accounts

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetInfrastructureAccountParams creates a new GetInfrastructureAccountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInfrastructureAccountParams() *GetInfrastructureAccountParams {
	return &GetInfrastructureAccountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInfrastructureAccountParamsWithTimeout creates a new GetInfrastructureAccountParams object
// with the ability to set a timeout on a request.
func NewGetInfrastructureAccountParamsWithTimeout(timeout time.Duration) *GetInfrastructureAccountParams {
	return &GetInfrastructureAccountParams{
		timeout: timeout,
	}
}

// NewGetInfrastructureAccountParamsWithContext creates a new GetInfrastructureAccountParams object
// with the ability to set a context for a request.
func NewGetInfrastructureAccountParamsWithContext(ctx context.Context) *GetInfrastructureAccountParams {
	return &GetInfrastructureAccountParams{
		Context: ctx,
	}
}

// NewGetInfrastructureAccountParamsWithHTTPClient creates a new GetInfrastructureAccountParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInfrastructureAccountParamsWithHTTPClient(client *http.Client) *GetInfrastructureAccountParams {
	return &GetInfrastructureAccountParams{
		HTTPClient: client,
	}
}

/*
GetInfrastructureAccountParams contains all the parameters to send to the API endpoint

	for the get infrastructure account operation.

	Typically these are written to a http.Request.
*/
type GetInfrastructureAccountParams struct {

	/* AccountID.

	   ID of the infrastructure account.
	*/
	AccountID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get infrastructure account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInfrastructureAccountParams) WithDefaults() *GetInfrastructureAccountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get infrastructure account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInfrastructureAccountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get infrastructure account params
func (o *GetInfrastructureAccountParams) WithTimeout(timeout time.Duration) *GetInfrastructureAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get infrastructure account params
func (o *GetInfrastructureAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get infrastructure account params
func (o *GetInfrastructureAccountParams) WithContext(ctx context.Context) *GetInfrastructureAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get infrastructure account params
func (o *GetInfrastructureAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get infrastructure account params
func (o *GetInfrastructureAccountParams) WithHTTPClient(client *http.Client) *GetInfrastructureAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get infrastructure account params
func (o *GetInfrastructureAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the get infrastructure account params
func (o *GetInfrastructureAccountParams) WithAccountID(accountID string) *GetInfrastructureAccountParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the get infrastructure account params
func (o *GetInfrastructureAccountParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WriteToRequest writes these params to a swagger request
func (o *GetInfrastructureAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param account_id
	if err := r.SetPathParam("account_id", o.AccountID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
