// Code generated by go-swagger; DO NOT EDIT.

package infrastructure_accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/zalando-incubator/cluster-lifecycle-manager/pkg/cluster-registry/models"
)

// GetInfrastructureAccountReader is a Reader for the GetInfrastructureAccount structure.
type GetInfrastructureAccountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInfrastructureAccountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetInfrastructureAccountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetInfrastructureAccountUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetInfrastructureAccountForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetInfrastructureAccountNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetInfrastructureAccountInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetInfrastructureAccountOK creates a GetInfrastructureAccountOK with default headers values
func NewGetInfrastructureAccountOK() *GetInfrastructureAccountOK {
	return &GetInfrastructureAccountOK{}
}

/*GetInfrastructureAccountOK handles this case with default header values.

Infrastructure account information.
*/
type GetInfrastructureAccountOK struct {
	Payload *models.InfrastructureAccount
}

func (o *GetInfrastructureAccountOK) Error() string {
	return fmt.Sprintf("[GET /infrastructure-accounts/{account_id}][%d] getInfrastructureAccountOK  %+v", 200, o.Payload)
}

func (o *GetInfrastructureAccountOK) GetPayload() *models.InfrastructureAccount {
	return o.Payload
}

func (o *GetInfrastructureAccountOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InfrastructureAccount)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInfrastructureAccountUnauthorized creates a GetInfrastructureAccountUnauthorized with default headers values
func NewGetInfrastructureAccountUnauthorized() *GetInfrastructureAccountUnauthorized {
	return &GetInfrastructureAccountUnauthorized{}
}

/*GetInfrastructureAccountUnauthorized handles this case with default header values.

Unauthorized
*/
type GetInfrastructureAccountUnauthorized struct {
}

func (o *GetInfrastructureAccountUnauthorized) Error() string {
	return fmt.Sprintf("[GET /infrastructure-accounts/{account_id}][%d] getInfrastructureAccountUnauthorized ", 401)
}

func (o *GetInfrastructureAccountUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInfrastructureAccountForbidden creates a GetInfrastructureAccountForbidden with default headers values
func NewGetInfrastructureAccountForbidden() *GetInfrastructureAccountForbidden {
	return &GetInfrastructureAccountForbidden{}
}

/*GetInfrastructureAccountForbidden handles this case with default header values.

Forbidden
*/
type GetInfrastructureAccountForbidden struct {
}

func (o *GetInfrastructureAccountForbidden) Error() string {
	return fmt.Sprintf("[GET /infrastructure-accounts/{account_id}][%d] getInfrastructureAccountForbidden ", 403)
}

func (o *GetInfrastructureAccountForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInfrastructureAccountNotFound creates a GetInfrastructureAccountNotFound with default headers values
func NewGetInfrastructureAccountNotFound() *GetInfrastructureAccountNotFound {
	return &GetInfrastructureAccountNotFound{}
}

/*GetInfrastructureAccountNotFound handles this case with default header values.

InfrastructureAccount not found
*/
type GetInfrastructureAccountNotFound struct {
}

func (o *GetInfrastructureAccountNotFound) Error() string {
	return fmt.Sprintf("[GET /infrastructure-accounts/{account_id}][%d] getInfrastructureAccountNotFound ", 404)
}

func (o *GetInfrastructureAccountNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetInfrastructureAccountInternalServerError creates a GetInfrastructureAccountInternalServerError with default headers values
func NewGetInfrastructureAccountInternalServerError() *GetInfrastructureAccountInternalServerError {
	return &GetInfrastructureAccountInternalServerError{}
}

/*GetInfrastructureAccountInternalServerError handles this case with default header values.

Unexpected error
*/
type GetInfrastructureAccountInternalServerError struct {
	Payload *models.Error
}

func (o *GetInfrastructureAccountInternalServerError) Error() string {
	return fmt.Sprintf("[GET /infrastructure-accounts/{account_id}][%d] getInfrastructureAccountInternalServerError  %+v", 500, o.Payload)
}

func (o *GetInfrastructureAccountInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetInfrastructureAccountInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
