// Code generated by go-swagger; DO NOT EDIT.

package node_pool_config_items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/zalando-incubator/cluster-lifecycle-manager/pkg/cluster-registry/models"
)

// AddOrUpdateNodePoolConfigItemReader is a Reader for the AddOrUpdateNodePoolConfigItem structure.
type AddOrUpdateNodePoolConfigItemReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddOrUpdateNodePoolConfigItemReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddOrUpdateNodePoolConfigItemOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAddOrUpdateNodePoolConfigItemBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewAddOrUpdateNodePoolConfigItemUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewAddOrUpdateNodePoolConfigItemForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewAddOrUpdateNodePoolConfigItemInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddOrUpdateNodePoolConfigItemOK creates a AddOrUpdateNodePoolConfigItemOK with default headers values
func NewAddOrUpdateNodePoolConfigItemOK() *AddOrUpdateNodePoolConfigItemOK {
	return &AddOrUpdateNodePoolConfigItemOK{}
}

/*AddOrUpdateNodePoolConfigItemOK handles this case with default header values.

The config items add/update request is accepted.
*/
type AddOrUpdateNodePoolConfigItemOK struct {
	Payload *models.ConfigValue
}

func (o *AddOrUpdateNodePoolConfigItemOK) Error() string {
	return fmt.Sprintf("[PUT /kubernetes-clusters/{cluster_id}/node-pools/{node_pool_name}/config-items/{config_key}][%d] addOrUpdateNodePoolConfigItemOK  %+v", 200, o.Payload)
}

func (o *AddOrUpdateNodePoolConfigItemOK) GetPayload() *models.ConfigValue {
	return o.Payload
}

func (o *AddOrUpdateNodePoolConfigItemOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ConfigValue)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddOrUpdateNodePoolConfigItemBadRequest creates a AddOrUpdateNodePoolConfigItemBadRequest with default headers values
func NewAddOrUpdateNodePoolConfigItemBadRequest() *AddOrUpdateNodePoolConfigItemBadRequest {
	return &AddOrUpdateNodePoolConfigItemBadRequest{}
}

/*AddOrUpdateNodePoolConfigItemBadRequest handles this case with default header values.

Invalid request
*/
type AddOrUpdateNodePoolConfigItemBadRequest struct {
	Payload *models.Error
}

func (o *AddOrUpdateNodePoolConfigItemBadRequest) Error() string {
	return fmt.Sprintf("[PUT /kubernetes-clusters/{cluster_id}/node-pools/{node_pool_name}/config-items/{config_key}][%d] addOrUpdateNodePoolConfigItemBadRequest  %+v", 400, o.Payload)
}

func (o *AddOrUpdateNodePoolConfigItemBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *AddOrUpdateNodePoolConfigItemBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddOrUpdateNodePoolConfigItemUnauthorized creates a AddOrUpdateNodePoolConfigItemUnauthorized with default headers values
func NewAddOrUpdateNodePoolConfigItemUnauthorized() *AddOrUpdateNodePoolConfigItemUnauthorized {
	return &AddOrUpdateNodePoolConfigItemUnauthorized{}
}

/*AddOrUpdateNodePoolConfigItemUnauthorized handles this case with default header values.

Unauthorized
*/
type AddOrUpdateNodePoolConfigItemUnauthorized struct {
}

func (o *AddOrUpdateNodePoolConfigItemUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /kubernetes-clusters/{cluster_id}/node-pools/{node_pool_name}/config-items/{config_key}][%d] addOrUpdateNodePoolConfigItemUnauthorized ", 401)
}

func (o *AddOrUpdateNodePoolConfigItemUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddOrUpdateNodePoolConfigItemForbidden creates a AddOrUpdateNodePoolConfigItemForbidden with default headers values
func NewAddOrUpdateNodePoolConfigItemForbidden() *AddOrUpdateNodePoolConfigItemForbidden {
	return &AddOrUpdateNodePoolConfigItemForbidden{}
}

/*AddOrUpdateNodePoolConfigItemForbidden handles this case with default header values.

Forbidden
*/
type AddOrUpdateNodePoolConfigItemForbidden struct {
}

func (o *AddOrUpdateNodePoolConfigItemForbidden) Error() string {
	return fmt.Sprintf("[PUT /kubernetes-clusters/{cluster_id}/node-pools/{node_pool_name}/config-items/{config_key}][%d] addOrUpdateNodePoolConfigItemForbidden ", 403)
}

func (o *AddOrUpdateNodePoolConfigItemForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddOrUpdateNodePoolConfigItemInternalServerError creates a AddOrUpdateNodePoolConfigItemInternalServerError with default headers values
func NewAddOrUpdateNodePoolConfigItemInternalServerError() *AddOrUpdateNodePoolConfigItemInternalServerError {
	return &AddOrUpdateNodePoolConfigItemInternalServerError{}
}

/*AddOrUpdateNodePoolConfigItemInternalServerError handles this case with default header values.

Unexpected error
*/
type AddOrUpdateNodePoolConfigItemInternalServerError struct {
	Payload *models.Error
}

func (o *AddOrUpdateNodePoolConfigItemInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /kubernetes-clusters/{cluster_id}/node-pools/{node_pool_name}/config-items/{config_key}][%d] addOrUpdateNodePoolConfigItemInternalServerError  %+v", 500, o.Payload)
}

func (o *AddOrUpdateNodePoolConfigItemInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *AddOrUpdateNodePoolConfigItemInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
