// Code generated by go-swagger; DO NOT EDIT.

package node_pool_config_items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteNodePoolConfigItemParams creates a new DeleteNodePoolConfigItemParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteNodePoolConfigItemParams() *DeleteNodePoolConfigItemParams {
	return &DeleteNodePoolConfigItemParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteNodePoolConfigItemParamsWithTimeout creates a new DeleteNodePoolConfigItemParams object
// with the ability to set a timeout on a request.
func NewDeleteNodePoolConfigItemParamsWithTimeout(timeout time.Duration) *DeleteNodePoolConfigItemParams {
	return &DeleteNodePoolConfigItemParams{
		timeout: timeout,
	}
}

// NewDeleteNodePoolConfigItemParamsWithContext creates a new DeleteNodePoolConfigItemParams object
// with the ability to set a context for a request.
func NewDeleteNodePoolConfigItemParamsWithContext(ctx context.Context) *DeleteNodePoolConfigItemParams {
	return &DeleteNodePoolConfigItemParams{
		Context: ctx,
	}
}

// NewDeleteNodePoolConfigItemParamsWithHTTPClient creates a new DeleteNodePoolConfigItemParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteNodePoolConfigItemParamsWithHTTPClient(client *http.Client) *DeleteNodePoolConfigItemParams {
	return &DeleteNodePoolConfigItemParams{
		HTTPClient: client,
	}
}

/*
DeleteNodePoolConfigItemParams contains all the parameters to send to the API endpoint

	for the delete node pool config item operation.

	Typically these are written to a http.Request.
*/
type DeleteNodePoolConfigItemParams struct {

	/* ClusterID.

	   ID of the cluster.
	*/
	ClusterID string

	/* ConfigKey.

	   Key for the config value.
	*/
	ConfigKey string

	/* NodePoolName.

	   Name of the node pool.
	*/
	NodePoolName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete node pool config item params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteNodePoolConfigItemParams) WithDefaults() *DeleteNodePoolConfigItemParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete node pool config item params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteNodePoolConfigItemParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete node pool config item params
func (o *DeleteNodePoolConfigItemParams) WithTimeout(timeout time.Duration) *DeleteNodePoolConfigItemParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete node pool config item params
func (o *DeleteNodePoolConfigItemParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete node pool config item params
func (o *DeleteNodePoolConfigItemParams) WithContext(ctx context.Context) *DeleteNodePoolConfigItemParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete node pool config item params
func (o *DeleteNodePoolConfigItemParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete node pool config item params
func (o *DeleteNodePoolConfigItemParams) WithHTTPClient(client *http.Client) *DeleteNodePoolConfigItemParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete node pool config item params
func (o *DeleteNodePoolConfigItemParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterID adds the clusterID to the delete node pool config item params
func (o *DeleteNodePoolConfigItemParams) WithClusterID(clusterID string) *DeleteNodePoolConfigItemParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the delete node pool config item params
func (o *DeleteNodePoolConfigItemParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithConfigKey adds the configKey to the delete node pool config item params
func (o *DeleteNodePoolConfigItemParams) WithConfigKey(configKey string) *DeleteNodePoolConfigItemParams {
	o.SetConfigKey(configKey)
	return o
}

// SetConfigKey adds the configKey to the delete node pool config item params
func (o *DeleteNodePoolConfigItemParams) SetConfigKey(configKey string) {
	o.ConfigKey = configKey
}

// WithNodePoolName adds the nodePoolName to the delete node pool config item params
func (o *DeleteNodePoolConfigItemParams) WithNodePoolName(nodePoolName string) *DeleteNodePoolConfigItemParams {
	o.SetNodePoolName(nodePoolName)
	return o
}

// SetNodePoolName adds the nodePoolName to the delete node pool config item params
func (o *DeleteNodePoolConfigItemParams) SetNodePoolName(nodePoolName string) {
	o.NodePoolName = nodePoolName
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteNodePoolConfigItemParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}

	// path param config_key
	if err := r.SetPathParam("config_key", o.ConfigKey); err != nil {
		return err
	}

	// path param node_pool_name
	if err := r.SetPathParam("node_pool_name", o.NodePoolName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
